Johan init
Mandrak-Kimigo/camap-docker pull request #5
Opened 2024-05-14 11:43 UTC by Johbrun

2024-05-14 12:05 UTC, Lythom requested changes

2024-05-14 12:05 UTC, Lythom commented on docker-compose.yml
> +    env_file: camap-ts/.env.docker
uniquement pour l'environnement de dev. Garder `.env` ici.

2024-05-14 12:05 UTC, Lythom commented on docker-compose.yml
> +    command: npm run start:dev
uniquement pour l'environnement de dev. Garder `start:prod` ici.

2024-05-14 12:05 UTC, Lythom commented on docker-compose.yml
> +    #   - ./camap-ts/packages/api-core/src:/srv/packages/api-core/src # src to watch
a supprimer, on a déjà `docker-compose.dev.yml` comme référence.

2024-05-14 12:05 UTC, Lythom commented on docker-compose.yml
> +    #   - ./camap-hx/config.xml:/srv/config.xml
a supprimer, on a déjà `docker-compose.dev.yml` comme référence.

2024-05-14 12:05 UTC, Lythom commented on mysql.Dockerfile
> +COPY ./my.cnf /etc/mysql/conf.d/
Ce changement correspond à un déplacement de my.cnf depuis camap-ts vers camap-docker.
Ok pour le changement, par contre je ne vois l'ajout du fichier dans cette PR. Un oubli ?

2024-05-14 12:05 UTC, Lythom commented on mysql.Dockerfile
> +# add permission to avoid " World-writable config file" warning
👌

2024-05-14 12:33 UTC, Johbrun commented on camap-hx.Dockerfile
> -COPY --chown=www-data:www-data ./camap-hx/www/ /srv/www/
Oui mais justement, ça a été remplacé par `COPY --chown=www-data:www-data ./camap-hx/ /srv/` :)

2024-05-14 12:38 UTC, Johbrun commented on mysql.Dockerfile
> +COPY ./my.cnf /etc/mysql/conf.d/
On avait ajouté dans la doc de copier le fichier,c'est pour ça. Par contre, je ne me souviens plus pourquoi... Donc dans le doute, je vais rollback

2024-05-14 12:46 UTC, Mandrak-Kimigo commented on mysql.Dockerfile
> +COPY ./my.cnf /etc/mysql/conf.d/
https://github.com/CAMAP-APP/camap-ts/pull/15#issuecomment-2110124478

2024-05-14 12:49 UTC, Mandrak-Kimigo commented on mysql.Dockerfile
> +# add permission to avoid " World-writable config file" warning
Ce sous-rep docker-compose est une scorie historique, c'est vrai que ça fait crassou.
Eventuellement on peut remonter le rep mysql d'un niveau sous camap-ts directement et virer le rep docker-compose mais my.cnf doit rester dans camap-ts (https://github.com/CAMAP-APP/camap-ts/pull/15#issuecomment-2110124478)

2024-05-14 12:52 UTC, Mandrak-Kimigo commented on README.md
> +- dans ```camap/camap-ts/.env```, remplacer ```loc-mysql``` par ```localhost``` (pour exécuter en local les commandes typeorm)
Je ne comprends pas l'objet de la modif, loc-mysql est le nom du container, pourquoi remplacer par localhost ?

2024-05-14 12:59 UTC, Mandrak-Kimigo commented on camap-hx.Dockerfile
> -COPY --chown=www-data:www-data ./camap-hx/www/ /srv/www/
Je préfèrerai qu'on laisse une copie explicite des rep nécessaires, ça évite les surprises ou de potentiels bugs/exploit liés à l'ajout de fichiers non désirés à la racine par ex.
D'un point de vue sécu c'est préférable. Si le code évolue et nécessite un fichier ou rep supplémentaire, charge à l'auteur de modifier le Dokerfile en conséquence.

2024-05-14 13:09 UTC, Mandrak-Kimigo requested changes
Il faudrait faire les pull-request sur CAMAP-APP/Camap-docker plutot sur Mandrak-Kimigo

J'avais créé ça sur Mandrak-Kimigo car à l'époque nous n'avions pas la main sur CAMAP-APP, c'est Alilo qui gérait.

Je vais supprimer le repo sur Mandrak-Kimigo

2024-05-14 13:27 UTC, Lythom commented on README.md
> +- dans ```camap/camap-ts/.env```, remplacer ```loc-mysql``` par ```localhost``` (pour exécuter en local les commandes typeorm)
> Je ne comprends pas l'objet de la modif, loc-mysql est le nom du container, pourquoi remplacer par localhost ?

Cela permet d'exécuter les scripts de synchronisation et migration typeorm depuis la machine hote. Utile lorsqu'on souhaite apporter des évolutions sur la base de données.

2024-05-14 13:38 UTC, Johbrun commented on camap-hx.Dockerfile
> -COPY --chown=www-data:www-data ./camap-hx/www/ /srv/www/
Ca marche, je rollback cette partie du coup !

2024-05-14 13:48 UTC, Mandrak-Kimigo commented on README.md
> +- dans ```camap/camap-ts/.env```, remplacer ```loc-mysql``` par ```localhost``` (pour exécuter en local les commandes typeorm)
Pourquoi ne pas plutot renseigner le fichier hosts en pointant 127.0.0.1 vers loc-mysql ?

2024-05-15 06:30 UTC, Lythom requested changes

2024-05-15 06:30 UTC, Lythom commented on camap-ts.Dockerfile
> -ENV THEME_ID=default
Je pensais que ces variables étaient redondantes avec les fichiers .env, mais en réalité elles permettent de générer les neomodules avec des paramètres correctes (URL publiques) pour la génération de liens de redirection.

Cela étant, elle sont redondantes si le fichier .env de référence est bien configuré (ce qui n'est pas le cas dans la version de référence: les variables API_HOSTNAME, CAMAP_HOST, CAMAP_BRIDGE_API, FRONT_URL et FRONT_GRAPHQL_URL devraient spécifier des URL publiques (comme ici) et non des URL interne (par ex., `API_HOSTNAME=nest-loc-camap` est incorrect).

@Johbrun Proposition d'évolution: 
- On garde bien la suppression des valeurs ici
- dans le .env de référence, utiliser les URL publiques de développement (celles ci-dessus sont bien)
- suppression de la manipulation concernant le .env.docker: on ne garder qu'un seul .env pour le docker et pour l'hote, et on ajoute `loc-mysql 127.0.0.1` au niveau du fichier host du système dans les consignes d'installation.

ça te semble ok ?

2024-05-15 06:33 UTC, Lythom commented on README.md
> +- dans ```camap/camap-ts/.env```, remplacer ```loc-mysql``` par ```localhost``` (pour exécuter en local les commandes typeorm)
Je n'avait pas pensé a utiliser le fichier hosts et en effet ça devrait fonctionner.
J'ai rencontré à l'instant une problématique croisée à ce fichier .env, je propose une évolution qui inclus l'utilisation d'un unique `.env` ici: https://github.com/Mandrak-Kimigo/camap-docker/pull/5#pullrequestreview-2057001440

2024-05-15 08:12 UTC, Mandrak-Kimigo commented on camap-ts.Dockerfile
> -ENV THEME_ID=default
Effectivement les valeurs doivent être redondantes puisqu'on s'en passe sur staging mais les valeurs sont **correctes**
MAIS
API_HOSTNAME et CAMAP_BRIDGE_API doivent référencer le container
CAMAP_HOST, FRONT_URL, FRONT_GRAPHQL_URL doivent référencer le hostname publique

2024-05-15 08:24 UTC, Mandrak-Kimigo commented on README.md
> +Vous pouvez générer un dump depuis l'environnement de staging.
Attention, l'environnement de "staging" est un environnement interne au serveur InterAMAP44 et n'est donc pas publique. Je ne pense pas qu'il faille le mentionner ici.

2024-05-15 09:40 UTC, closed without merging

2024-05-15 12:35 UTC, Lythom commented on camap-ts.Dockerfile
> -ENV THEME_ID=default
Ok bien vu @Mandrak-Kimigo, pour moi CAMAP_BRIDGE_API était utilisé pour générer des URL, mais après vérification c'est utilisé directement via Curl dans BridgeService.hx donc utilisation uniquement interne à l'app. Et API_HOSTNAME uniquement pour démarrer le serveur (ça n'a pas beaucoup d'importance mais l'url interne c'est bien).